id/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #首页
    url(r'^$', views.index, name='index'),
]

id_sys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('id.urls', namespace='id'))
]

id/models.py
from django.db import models

# Create your models here.
class Provinces(models.Model):
    '''省ID号'''
    provinceid = models.CharField(max_length=50)
    province = models.CharField(max_length=50)

    def __str__(self):
        return self.province

class Cities(models.Model):
    '''市ID号'''
    cityid = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    provinceid = models.CharField(max_length=50)

    def __str__(self):
        return self.city


class Areas(models.Model):
    '''区域ID号'''
    areaid = models.CharField(max_length=50)
    area = models.CharField(max_length=50)
    cityid = models.CharField(max_length=50)

    def __str__(self):
        return self.area

class Id_number(models.Model):
    '''身份证号'''
    id_numbers = models.CharField(max_length=18)

    def __str__(self):
        return self.id_numbers

users/models.py
from django.db import models

# Create your models here.

id/forms.py
from django import forms

from .models import Id_number

class IdForm(forms.ModelForm):
    class Meta:
        model = Id_number
        fields = ['id_numbers']
        labels = {'id_numbers':''}

id/views.py
from django.shortcuts import render

from .forms import IdForm
from .function import *

# Create your views here.
def index(request):
    '''首页'''
    if request.method != 'POST':
        form = IdForm()
        id_check = 'message'
    else:
        form = IdForm(data=request.POST)
        if form.is_valid():
            form.save()
            #获取身份证信息
            id_numbers = request.POST['id_numbers']
            #检查输入是否有误
            if check_id_numbers_wrong(id_numbers) \
                    or check_test_code_wrong(id_numbers):
                id_check = 'wrong'
            else:
                #获取身份证信息
                #地址
                id_adress = get_id_adress(id_numbers)
                #出生日期
                id_age = get_id_age(id_numbers)
                #性别
                id_sex = get_id_sex(id_numbers)

                id_check = {'adress':id_adress, 'age':id_age, 'sex':id_sex}
        else:
            id_check = 'wrong'

    context = {'form':form, 'id_check':id_check}
    return render(request, 'id/index.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

id/templates/id/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>身份证查询系统</title>

    <!-- 用link导入css样式 -->
    {% load static %}
    <link href="{% static 'id/css/my_style.css' %}" type="text/css" rel="stylesheet" />
    <script src="{% static 'id/js/get_time.js' %}" type="text/javascript"></script>

</head>
<body>
<h1 class="center_with_color">简单的身份证查询系统</h1>

{% block body %}
{% endblock body %}

{% block result %}
{% endblock result %}

{% block time %}
{% endblock time %}

</body>
</html>

id/templates/id/index.html
{% extends "id/base.html" %}

{% block body %}
    <br>
    <br>
    <br>
    <form class="center" action="{% url 'id:index' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button name='submit'>提交</button>
    </form>

{% endblock body %}

{% block result %}
    <div class="center">
    {% if id_check == 'message' %}
        <p>请输入身份证号码，提交后会在这里显示结果！</p>
    {% endif %}

    {% if id_check == 'wrong' %}
        <p>你输入的身份证信息有误！</p>
        <p>不要闹了，请输入正确的身份证信息！</p>
    {% endif %}

    {% if id_check != 'wrong' and id_check != 'message' %}
        <p>身份证合法！</p>

        <p>性别：{{ id_check.sex }}</p>
        <p>年龄：{{ id_check.age.3 }}</p>
        <p>出生日期：{{ id_check.age.0 }}年{{ id_check.age.1 }}月{{ id_check.age.2 }}日</p>
        <p>身份证归属地：
        {% for id_adress in id_check.adress %}
            {{ id_adress }}
        {% endfor %}
        </p>
    {% endif %}
    </div>
{% endblock result %}

{% block time %}
    <!-- 在html中用系统函数直接调用time()函数，不需要onclick -->
    <script type = "text/javascript">
        window.onload = function()
        {
            time();
        }
    </script>
    <div class="center">
    <div id="timeShow" class="time"></div>
    </div>
{% endblock time %}